### ISSUE TITLE
Typo-quick fix: "Louvre"

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/git-version-control-getting-code-with-git#2]
Hi, just a quick typo on first line "Louve" to "Louvre". 
********
It's like saying "Hey, can I have the Louvre's version of The Mona Lisa?" The Louve would say, "No." If you were to create a perfect online duplicate by forking it from louvre/mona_lisa to your-name/mona_lisa, and then were to clone from that remote repository, then the Louvre can keep their copy and you can update your copy as you choose.

**Comment by Sdcrouse** [comment]
I have fixed this in a pull request here: [https://github.com/learn-co-students/git-version-control-getting-code-with-git-v-000/pull/1](https://github.com/learn-co-students/git-version-control-getting-code-with-git-v-000/pull/1). The ball is in their court, now (I'm only a student, not a Flatiron Engineer).

---Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback. When making pull requests, ensure that they are being submitted to `learn-co-curriculum` so that the parent version of the repo has the updates. They've been committed to this lesson.
Thanks for your contribution!
