### ISSUE TITLE
The sections that mention forking are a bit misleading.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/git-version-control-getting-code-with-git#3]
Hello. The lesson mentions the "git fork" command throughout the lesson, but never explains how to use it. Instead, the lesson shows how to use GitHub's "Fork" button.

Technically, there IS a Git command called "git fork", but I don't think it's supposed to be in this lesson. I have fixed this in a pull request (along with a small typo) here: [https://github.com/learn-co-students/git-version-control-getting-code-with-git-v-000/pull/1](https://github.com/learn-co-students/git-version-control-getting-code-with-git-v-000/pull/1).

Thanks for looking into this!

Sdcrouse

**Comment by drakeltheryuujin** [comment]
Integrated in with #2
