### ISSUE TITLE
Lesson doesn't match new github interface

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/git-version-control-getting-code-with-git#8]
Screenshots and text in the "Copy a Repository to Your Local Machine with git clone" section need to be updated. Also, one of the images isn't rendering

**Comment by maxwellbenton** [comment]
Hey Liz,

I've updated the images to reflect the new layout, so this should be all set now. The second image was indented too far, as well, causing GitHub to misinterpret the markdown.
